# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 30
style = "bold red"

[character]
success_symbol = "[âœ](bold green)" # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = "[âœ–](bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = '([\[$duration\]]($style))'

[directory]
truncation_length = 5
format = '([\[$path\]]($style)[$lock_symbol]($lock_style) )'

[fill]
symbol = " "

[gcloud]
disabled = true

[git_branch]
format = '([\[$symbol$branch(:$remote_branch)\]]($style) )'
symbol = "ğŸŒ±"

[git_state]
format = '\([$state($progress_current of $progress_total)]($style)\) '

[git_status]
conflicted = "ğŸ’¥"
ahead = "ğŸï¸ğŸ’¨Ã—${count}"
behind = "ğŸ¢Ã—${count} "
diverged = "ğŸ”± ğŸï¸ğŸ’¨Ã—${ahead_count} ğŸ¢Ã—${behind_count}"
untracked = "ğŸ›¤ï¸Ã—${count}"
stashed = "ğŸ“¦"
modified = "ğŸ“Ã—${count}"
staged = "ğŸ—ƒï¸Ã—${count}"
renamed = "ğŸ“›Ã—${count}"
deleted = "ğŸ—‘ï¸Ã—${count}"
style = "bright-white"

[golang]
format = '([\[$symbol($version)\]]($style) )'

[gradle]
format = '([\[$symbol($version)\]]($style) )'

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[java]
format = '([\[$symbol($version)\]]($style) )'

[julia]
format = "[$symbol$version]($style) "
symbol = "à®ƒ "
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[nodejs]
format = '([\[$symbol$version\]]($style) )'

[package]
format = '([\[$symbol$version\]]($style) )'

[python]
format = '([\[$symbol$version\]]($style) )'

[rust]
format = '([\[$symbol($version)\]]($style) )'

[time]
time_format = "%T"
format = '([\[ğŸ•™ $time\]]($style) )'
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"

